// types.ts (updated version)

export enum UserRole {
  ADMIN = 'ADMIN',
  CENTRAL_ADMIN = 'CENTRAL_ADMIN',
  STORE_MANAGER = 'STORE_MANAGER'
}

export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}

export interface Store {
  id: string;          // UUID generated by Supabase
  name: string;
  location: string;
  is_central?: boolean; // Add this if you are using the logic from your stores.service
  created_at?: string;  // ISO string from Supabase
}

export interface PurchaseItem {
  supplier?: string;
  description: string;
  quantity: number;
  unit: string;
  cost: number;
  sellingPrice: number;
}

export interface Purchase {
  id?: string;                    // uuid
  date: string;                  // keep as 'YYYY-MM-DD' or change to full ISO if needed
  store_id?: string;
  purchase_items?: PurchaseItem[];        // jsonb → keep as array
  receipt_image?: string;         // base64 or URL
  total_cost: number;
  is_quick_entry?: boolean;
  created_at?: string;           // add if you want Supabase timestamps
}

export interface ShiftData {
  posSales: number;
  cardSales: number;
  cashCounted: number;
  openingFund: number;
  expectedCash: number;
  difference: number;
  employeeName: string;
  shiftTime: string;
}

export interface Sale {
  id: string;
  date: string;                  // 'YYYY-MM-DD' or full ISO
  storeId: string;
  amount: number;
  morningShift: ShiftData;
  afternoonShift: ShiftData;
  receiptImage?: string;
  created_at?: string;           // optional
}

export interface Expense {
  id: string;
  date: string;
  storeId: string;
  category: string;
  description: string;
  amount: number;
  created_at?: string;
}

export interface User {
  id: string;                    // uuid (from auth.users or your table)
  username: string;
  name: string;
  password?: string;             // only if you store it (not recommended with Supabase Auth)
  role: UserRole;
  assigned_store_id?: string;
  created_at?: string;
}

export interface Product {
  id: string;
  name: string;
  unit: string;
  costPrice: number;
  sellingPrice: number;
  minStockLevel: number;
  created_at?: string;
}

export interface Stock {
  product_id: string;
  store_id: string;
  quantity: number;
}

export interface StockTransfer {
  id: string;
  date: string;                  // 'YYYY-MM-DD' or ISO
  productId: string;
  quantity: number;
  fromStoreId: string;
  toStoreId: string;
  created_at?: string;
}

export interface ProductRequestItem {
  description: string;
  quantity: number;
  unit: string;
}

export interface ProductRequest {
  id: string;
  date: string;
  storeId: string;
  items?: ProductRequestItem[];
  receiptImage?: string;
  status: RequestStatus;
  note?: string;
  created_at?: string;
}

export interface WastageItem {
  time: string;
  productId: string;
  productName: string;
  reason: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface WastageReport {
  id: string;
  date: string;
  storeId: string;
  responsible: string;
  items: WastageItem[];
  totalWastage: number;
  receiptImage?: string;
  created_at?: string;
}


export interface Supplier {
  id: string;
  created_at?: string;
  name: string;
  contact_person: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  category: string;
  is_active: boolean;
}